@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as Logic LOGIC_COLOR
participant ":SharkieParser" as SharkieParser LOGIC_COLOR
participant ":WalletExpenseCommandParser" as WalletExpenseCommandParser LOGIC_COLOR
participant "w:WalletExpenseCommand" as WalletExpenseCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "e:Expense" as Expense MODEL_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":Wallet" as Wallet MODEL_COLOR
participant ":TransactionList" as TransactionList MODEL_COLOR
end box

[-> Logic : execute()
activate Logic

Logic -> SharkieParser : parseCommand()
activate SharkieParser

create WalletExpenseCommandParser
SharkieParser -> WalletExpenseCommandParser
activate WalletExpenseCommandParser

WalletExpenseCommandParser --> SharkieParser
deactivate WalletExpenseCommandParser

SharkieParser -> WalletExpenseCommandParser : parse()
activate WalletExpenseCommandParser

create WalletExpenseCommand
WalletExpenseCommandParser -> WalletExpenseCommand
activate WalletExpenseCommand

create Expense
WalletExpenseCommand -> Expense
activate Expense

Expense --> WalletExpenseCommand : e
deactivate Expense

WalletExpenseCommand --> WalletExpenseCommandParser : w
deactivate WalletExpenseCommand

WalletExpenseCommandParser --> SharkieParser : w
deactivate WalletExpenseCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
WalletExpenseCommandParser -[hidden]-> SharkieParser
destroy WalletExpenseCommandParser

SharkieParser --> Logic : w
deactivate SharkieParser

Logic -> WalletExpenseCommand : execute()
activate WalletExpenseCommand

WalletExpenseCommand -> ModelManager : addExpense(e)
activate ModelManager

ModelManager -> Wallet : addExpense(e)
activate Wallet

Wallet -> TransactionList : addTransaction(e)
activate TransactionList

TransactionList --> Wallet
deactivate TransactionList

Wallet --> ModelManager
deactivate Wallet

ModelManager --> WalletExpenseCommand
deactivate ModelManager

create CommandResult
WalletExpenseCommand -> CommandResult
activate CommandResult

CommandResult --> WalletExpenseCommand : result
deactivate CommandResult

WalletExpenseCommand --> Logic : result
deactivate WalletExpenseCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
WalletExpenseCommand -[hidden]-> Logic
destroy WalletExpenseCommand
[<--Logic : result
deactivate Logic

@enduml
