@startuml
title Activity: Recording an expense
start
:User enters the expense command;

if () then ([description or amount is not specified or is invalid])
    :Display an error message;
else ([else])
    if () then ([date is specified])
        :Set the date to the specified date;
    else ([else])
        :Set the date to the current date;
    endif
    if () then ([tag is specified])
        :Set the tag to the specified tag;
    else ([else])
        :Set the date to a default tag (Misc);
    endif
    :Add a new expense to the Wallet;
endif
stop
@enduml
