@startuml
!include style.puml
skinparam padding 2
skinparam minClassWidth 80
skinparam arrowFontSize 10
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Reminder {
Class Reminder
Class ConfirmationEmail
}

Package Person {
Class User
Class Person
Class Email
Class Name
}

Reminder o--> "1" User
Reminder o--> "1" Person
ConfirmationEmail o--> "1" Name
ConfirmationEmail o--> "1" Email

@enduml
