@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyWallet <<Interface>>
Interface ReadOnlyUserData <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class Wallet
Class UserData
Class ReadOnlyAddressBook
Class ReadOnlyWallet
Class ReadOnlyUserData
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class Person
Class UniquePersonList
Class User
}

Package Transaction {
Class TransactionList
abstract Transaction <<abstract>>
Class Expense
Class Income
Class Debt
Class Loan
Class Budget
Class BudgetList
}

Package Reminder {
Class Reminder
Class ConfirmationEmail
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
Wallet .up.|> ReadOnlyWallet
UserData .up.|> ReadOnlyUserData

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" UserData
ModelManager o--> "1" AddressBook
ModelManager o--> "1" Wallet
ModelManager o--> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person

UserData *--> "1" User

Wallet *--> "2" TransactionList
Wallet *--> "1" BudgetList
BudgetList o--> "*" Budget
TransactionList o--> "*" Expense
TransactionList o--> "*" Income
Expense -up-|> Transaction
Income -up-|> Transaction
Debt -up-|> Transaction
Loan -up-|> Transaction

Person *-[hidden]-> "*" Tag
Transaction *-[hidden]-> "1" Tag

Reminder o-up-> "1" User
Reminder o-up-> "1" Person

Person -[hidden]right-> User
UserPrefs -[hidden]right-> Wallet
Wallet -[hidden]right-> AddressBook
AddressBook -[hidden]right-> UserData
UniquePersonList -[hidden]right-> User
Transaction -[hidden]right-> TransactionList
Loan -[hidden]right-> Debt
Debt -[hidden]right-> Income
Income -[hidden]right-> Expense
Expense -[hidden]right-> Person
Debt -[hidden]down-> Tag
Loan -[hidden]down-> Tag


@enduml
