@startuml
!include style.puml
skinparam padding 2
skinparam minClassWidth 80
skinparam arrowFontSize 10
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Transaction {
Class TransactionList
abstract Transaction <<abstract>>
Class Expense
Class Income
Class Debt
Class Loan
Class Amount
Class Budget
Class BudgetList
Class Month
Class Year

Interface WalletPredicate <<Interface>>
Class AmountContainsKeywordsPredicate
Class DateContainsKeywordsPredicate
Class DescriptionContainsKeywordsPredicate
Class TagContainsKeywordsPredicate
}

Class HiddenWallet #FFFFFF
Class Person #FFFFFF
HiddenWallet --> "1" TransactionList
HiddenWallet --> "1" BudgetList
Person --> "*" Debt
Person --> "*" Loan
BudgetList o--> "*" Budget
TransactionList o--> "*" Expense
TransactionList o--> "*" Income
Expense .up.|> Transaction
Income .up.|> Transaction
Debt .up.|> Transaction
Loan .up.|> Transaction
Budget *--> Amount
Budget *--> Month
Budget *--> Year

DescriptionContainsKeywordsPredicate .up.|> WalletPredicate
AmountContainsKeywordsPredicate .up.|> WalletPredicate
DateContainsKeywordsPredicate .up.|> WalletPredicate
TagContainsKeywordsPredicate .up.|> WalletPredicate

WalletPredicate -[hidden]left-> BudgetList
DescriptionContainsKeywordsPredicate -[hidden]down-> AmountContainsKeywordsPredicate
DescriptionContainsKeywordsPredicate -[hidden]left-> DateContainsKeywordsPredicate
DateContainsKeywordsPredicate -[hidden]down-> TagContainsKeywordsPredicate
AmountContainsKeywordsPredicate -[hidden]left-> TagContainsKeywordsPredicate

@enduml
