@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyWallet <<Interface>>
Interface ReadOnlyUserData <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class Wallet
Class UserData
Class ReadOnlyAddressBook
Class ReadOnlyWallet
Class ReadOnlyUserData
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class Person
Class UniquePersonList

Package User {
Class User
}
}

Package Transaction {
Class TransactionList
Interface Transaction <<Interface>>
Class Expense
Class Income
Class Debt
Class Loan
Class Budget
Class BudgetList
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
Wallet .up.|> ReadOnlyWallet
UserData .up.|> ReadOnlyUserData

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" UserData
ModelManager o--> "1" AddressBook
ModelManager o--> "1" Wallet
ModelManager o--> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person

UserData *--> "1" User

Wallet *--> "1" TransactionList
Wallet *--> "1" BudgetList
BudgetList o--> "*" Budget
TransactionList o--> "*" Expense
TransactionList o--> "*" Income
Expense .up.|> Transaction
Income .up.|> Transaction
Debt .up.|> Transaction
Loan .up.|> Transaction

ModelManager -->"1" Person : filtered list

UserPrefs -[hidden]right-> Wallet
Wallet -[hidden]right-> AddressBook
AddressBook -[hidden]right-> UserData
Person -[hidden]right-> UniquePersonList
UniquePersonList -[hidden]right-> User
@enduml
