@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyWallet <<Interface>>
Interface ReadOnlyUserData <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class Wallet
Class UserData
Class ReadOnlyAddressBook
Class ReadOnlyWallet
Class ReadOnlyUserData
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class UniquePersonList
Class User
}

Package Transaction {
Class "TransactionList" as TransactionListIncome
Class "TransactionList" as TransactionListExpense
Class BudgetList
Class Expense
Class Income
abstract "{abstract}\nTransaction" as Transaction
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
Wallet .up.|> ReadOnlyWallet
UserData .up.|> ReadOnlyUserData

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" UserData
ModelManager o--> "1" AddressBook
ModelManager o--> "1" Wallet
ModelManager o--> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList

UserData *--> "1" User

Wallet *--> "1" TransactionListIncome
Wallet *--> "1" TransactionListExpense
Wallet *--> "1" BudgetList

TransactionListExpense o--> "*" Expense
TransactionListIncome o--> "*" Income

Expense -up-|> Transaction
Income -up-|> Transaction

Person -[hidden]right-> User
UserPrefs -[hidden]right-> Wallet
Wallet -[hidden]right-> AddressBook
AddressBook -[hidden]right-> UserData
UniquePersonList -[hidden]right-> User


@enduml
