@startuml
title Activity: Recording a debt
start
:User enters the owe command;

if () then ([name, amount or index is not specified or is invalid])
    :Display an error message;
else ([else])
    if () then ([date is specified])
        :Set the date to the specified date;
    else ([else])
        :Set the date to the current date;
    endif
    if () then ([index of person is out of bound])
        :Display an error message;
    else ([else])
        :Add debt to the person;
        :Update the contact list;
    endif
endif
stop
@enduml
