@startuml
title Activity: Recording the amount of money received
start
:User executes a received command;

if () then ([Person index entered \nby the user is invalid])
    :Display an error message;
else ([else])
    if () then ([User did not lend the \nindicated Person money])
        :Display an error message;
    else ([else])
        if () then ([User asked to edit specific\n Loan of the Person])
            :Remove the specified \nLoan from the Person;
        else ([else])
            :Remove all Loans \nfrom the Person;
        endif
        :Update the contact list;
    endif
endif
stop
@enduml
