@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>
Interface WalletStorage <<Interface>>
Interface UserDataStorage <<Interface>>
Interface JsonAdaptedTransaction <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage
Class JsonWalletStorage
Class JsonUserDataStorage

StorageManager .left.|> Storage
StorageManager o-up-> UserPrefsStorage
StorageManager o-down-> AddressBookStorage
StorageManager o-right-> WalletStorage
StorageManager o-up-> UserDataStorage
UserDataStorage -right[hidden]- WalletStorage

JsonUserPrefsStorage .right.|> UserPrefsStorage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage .right.> JsonSerializableAddressBook
JsonSerializableAddressBook .right.> JsonAdaptedPerson
JsonAdaptedPerson .right.> JsonAdaptedTag

JsonWalletStorage .left.|> WalletStorage
JsonWalletStorage .right.> JsonSerializableWallet
JsonSerializableWallet .down.> JsonAdaptedTransaction
JsonAdaptedTransaction .down.> JsonAdaptedTag
JsonAdaptedXYZ .right.|> JsonAdaptedTransaction

JsonUserDataStorage .left.|> UserDataStorage
JsonUserDataStorage .right.> JsonAdaptedUser
@enduml
