@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage <<Rectangle>>{
Interface Storage <<Interface>>
Class StorageManager

Package UserPrefs {
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Package UserData {
Interface UserDataStorage <<Interface>>
Class JsonUserDataStorage
Class JsonAdaptedUser
}

Package AddressBook {
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
}

Package Wallet {
Interface WalletStorage <<Interface>>
Class JsonWalletStorage
Class JsonSerializableWallet
Interface JsonAdaptedTransaction <<Interface>>
Class JsonAdaptedXYZ
}

Package Tag {
Class JsonAdaptedTag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager o-up-> UserPrefsStorage
StorageManager o-down-> AddressBookStorage
StorageManager o-right-> WalletStorage
StorageManager o-up-> UserDataStorage
UserDataStorage -right[hidden]- WalletStorage

JsonUserPrefsStorage .right.|> UserPrefsStorage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage .right.> JsonSerializableAddressBook
JsonSerializableAddressBook .right.> JsonAdaptedPerson
JsonAdaptedPerson .right.> JsonAdaptedTag

JsonWalletStorage .left.|> WalletStorage
JsonWalletStorage .right.> JsonSerializableWallet
JsonSerializableWallet .down.> JsonAdaptedTransaction
JsonAdaptedTransaction .down.> JsonAdaptedTag
JsonAdaptedXYZ .right.|> JsonAdaptedTransaction

JsonUserDataStorage .left.|> UserDataStorage
JsonUserDataStorage .right.> JsonAdaptedUser
@enduml
