@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>
Interface WalletStorage <<Interface>>
Interface UserDataStorage <<Interface>>
Interface JsonAdaptedTransaction <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage
Class JsonWalletStorage
Class JsonUserDataStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> AddressBookStorage
StorageManager o-up-> WalletStorage
StorageManager o-up-> UserDataStorage
UserDataStorage -right[hidden]- WalletStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonAddressBookStorage .left.|> AddressBookStorage
JsonAddressBookStorage .down.> JsonSerializableAddressBook
JsonSerializableAddressBook .right.> JsonAdaptedPerson
JsonAdaptedPerson .right.> JsonAdaptedTag

JsonWalletStorage .left.|> WalletStorage
JsonWalletStorage .right.> JsonSerializableWallet
JsonSerializableWallet .right.> JsonAdaptedTransaction
JsonAdaptedTransaction .down...> JsonAdaptedTag
JsonAdaptedTransaction .down..> TransactionDescriptor
JsonAdaptedLoan .down.|> JsonAdaptedTransaction
JsonAdaptedDebt .up.|> JsonAdaptedTransaction
JsonAdaptedExpense .left.|> JsonAdaptedTransaction
JsonAdaptedIncome .down.|> JsonAdaptedTransaction

JsonUserDataStorage .down.|> UserDataStorage
JsonUserDataStorage .right.> JsonAdaptedUser
@enduml
