= Grace Pan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Sharkie

---

== Overview

*Sharkie* is a desktop expense tracker application.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions *[To be updated]*

* *Major enhancement*:
. Added *the ability to list out all transactions in the wallet and the UI for it*
*** What it does: allows the user to list out all transactions, which includes expenses and income.
*** Justification: This feature improves the product significantly because it allows the user to view all their transactions in their wallet.
*** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to the UI, including the need to add a tab view to view the Wallet and Address Book separately.
. Added *the ability to edit the transactions in the wallet*
*** What it does: allows the user to edit the transactions already in the wallet, which includes expenses and income.
*** Justification: This feature improves the product significantly because it allows the user to edit the information they already keyed in, in case of any mistakes made or updates needed to the transactions.
*** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
. Added *the ability to delete the transactions in the wallet*
*** What it does: allows the user to delete the transactions already in the wallet, which includes expenses and income.
*** Justification: This feature improves the product significantly because it allows the user to delete the information they already keyed in, in case of any mistakes made.
*** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
. Added *the ability to find transactions in the wallet*
*** What it does: allows the user to find transactions already in the wallet, which includes expenses and income.
*** Justification: This feature improves the product significantly because it allows the user to find the information they already keyed in, according to the description of the transactions.
*** Highlights: This enhancement affects existing commands and commands to be added in future.
It required an in-depth analysis of design alternatives.
* *Minor enhancement*:
. Added *the ability to clear all transactions in the wallet*

* *Other contributions*:

** Project management:
*** Set deliverable and deadlines for the group.
** Enhancements to features:
***  (Pull requests https://github.com/AY1920S2-CS2103T-W12-3/main/pull/52[#52],
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/54[#54], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/61[#61],
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/66[#66], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/102[#102], ,
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/110[110], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/115[#115], ,
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/117[#117], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/121[#121],
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/122[#122], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/127[#127],
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/128[#128], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/174[#174],
https://github.com/AY1920S2-CS2103T-W12-3/main/pull/245[#245], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/248[#248])
** Documentation:
*** Updated the User Guide to include more commands, updated Quick Start, and Updated ContactUs: https://github.com/AY1920S2-CS2103T-W12-3/main/pull/52[#52]
*** Did cosmetic tweaks to existing contents of the User Guide and Quick Start: https://github.com/AY1920S2-CS2103T-W12-3/main/pull/54[#54]
*** Fixed errors in Developer Guide: https://github.com/AY1920S2-CS2103T-W12-3/main/pull/184[#184]
** Community:
*** PRs reviewed (with non-trivial review comments) : https://github.com/AY1920S2-CS2103T-W12-3/main/pull/71[#71], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/95[#95], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/101[#101], https://github.com/AY1920S2-CS2103T-W12-3/main/pull/118[#118],  https://github.com/AY1920S2-CS2103T-W12-3/main/pull/140[#140]
*** Contributed to forum discussions (examples:  https://github.com/nus-cs2103-AY1920S2/forum/issues/25[#25])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/AY1920S2-CS2103T-W16-3/main/issues/123[DG Suggestions])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=quickStart]

include::../UserGuide.adoc[tag=walletList]

include::../UserGuide.adoc[tag=walletedit]

include::../UserGuide.adoc[tag=walletfind]

include::../UserGuide.adoc[tag=walletdelete]

include::../UserGuide.adoc[tag=walletClear]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=productScope]

include::../DeveloperGuide.adoc[tag=userStories]

include::../DeveloperGuide.adoc[tag=walletEdit_implementation]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
