= Chen Syin Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Sharkie

---

== Overview

*Sharkie* is a desktop expense tracker application. The user interacts with it using a CLI,
and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:

** Added `*lend*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#87])
*** What it does: Allows the user to record the amount of money lent to other people in the address book.
*** Justification: This is one of the key features of Sharkie, which records the flow of money between the user and
the people in the address book.
** Added `*received*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#98])
*** What it does: Allows the user to record that a person, which the user lent has returned the amount of money.
*** Justification: This is an essential update, which allows the user to remove the loans recorded by the
`lend` command.
** Added *user data storage* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#95])
*** What it does: Stores user data, such as name, phone and e-mail address.
*** Justification: The storage of user data is important, as the user details are required to use the `remind`
and `remindall` commands.
** Added `*remind*` and `*remindall*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#95])
*** What it does: Allows the user to send reminders to the people, who has yet return the amount of money they lent via email.
*** Justification: This is one of the main features of Sharkie, which allows the interaction between the user and
the people in the address book.
*** Credits: _javax.mail_ is used in the implementation of this feature.

* *Other contributions*:

** Project management:
*** Finalized and tagged `v1.1` and `v1.2`.
** Documentation:
*** Updated the product website's heading and navigation bar: (Pull request
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#44], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#81])
*** Edited various parts of the User Guide: (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#49])
*** Added use cases and updated the Design and Implementation part of the Developer Guide:
(Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#51],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#132], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#134])
** Community:
*** PRs reviewed (with non-trivial review comments): (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#92],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#100], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#104],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#115])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=about]

== Features

include::../UserGuide.adoc[tag=expenditureAndIncome]

== Commands

include::../UserGuide.adoc[tag=peopleadd]

include::../UserGuide.adoc[tag=peopleremind]

include::../UserGuide.adoc[tag=peopleremindall]

include::../UserGuide.adoc[tag=peoplefind]

== FAQ

include::../UserGuide.adoc[tag=editing-user-data]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Design

include::../DeveloperGuide.adoc[tag=model-design]

== Implementation

include::../DeveloperGuide.adoc[tag=received_implementation]

include::../DeveloperGuide.adoc[tag=useCases]

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
