= Chen Syin Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Sharkie

---

== Overview

*Sharkie* is a desktop expense tracker application. The user interacts with it using a CLI,
and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:

** *Added* `*lend*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#87])
*** What it does: Allows the user to record the amount of money lent to other people in the address book.
*** Justification: This is one of the key features of Sharkie, which records the flow of money between the user and
the people in the address book.
*** Highlights: This command involves both `Transactions` and `Person` models, considerations have to made on how to
use both of the models without changing their purposes or properties.
** *Added* `*received*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#98])
*** What it does: Allows the user to record that a person, who the user lent to has returned the amount of money.
*** Justification: This is an essential update, which allows the user to remove the `loans` recorded by the
`lend` command.
*** Highlights: Considerations were needed during the implementation of this feature, to preserve the immutable
property of `Person`.
** *Added user data storage* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#95])
*** What it does: Stores user data, such as name, phone and e-mail address.
*** Justification: The storage of user data is important, as the user details are required to use the `remind`
and `remindall` commands.
*** Highlights: This update was challenging, an entire new storage need to be built to store the user data, as the
data needed to be stored differs from those in address book.
** *Added* `*remind*` *and* `*remindall*` *command* (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#95])
*** What it does: Allows the user to send reminders to the people, who has yet return the amount of money they lent via email.
*** Justification: This is one of the main features of Sharkie, which allows the interaction between the user and
the people in the address book.
*** Highlights: The implementation of this feature was new to me, as it involves the usage of the internet and the
connection to e-mail servers.
*** Credits: _javax.mail_ is used in the implementation of this feature.

* *Minor enhancement*:

** Add progress indicator for command execution, to indicate that the application is not hanging
during execution of commands, which take some time to run, such as `people remind`. (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#148])

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=syinyichen&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=syinyichen&tabRepo=AY1920S2-CS2103T-W12-3%2Fmain%5Bmaster%5D[Code]]

* *Other contributions*:
** Enhancements to existing features:
*** Fixed JavaFX thread issues. (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#178])
*** Improved GUI of Edit User Data Window and Help Window. (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#178])
*** Made `people's tags` uneditable. (Pull request https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#183])
** Project management:
*** Finalized and tagged `v1.1` - `v1.3` (3 versions) on Github.
*** Managed release of `v1.2.1` - `v1.3` (2 releases) on Github.
** Documentation:
*** Updated the product website's heading and navigation bar. (Pull requests
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#44], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#81])
*** Edited About, Features, Commands and FAQ sections of the User Guide. (Pull requests https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#49])
*** Added use cases in the appendix, updated Design and Implementation sections of the Developer Guide.
(Pull requests https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#51],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#132], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#134])
** Community:
*** PRs reviewed (with non-trivial review comments). (Pull requests https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#92],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#100], https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#104],
https://github.com/AY1920S2-CS2103T-W12-3/main/pulls[#115], ...)

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=about]

== Features

include::../UserGuide.adoc[tag=expenditureAndIncome]

== Commands

include::../UserGuide.adoc[tag=peopleadd]

include::../UserGuide.adoc[tag=peopleremind]

include::../UserGuide.adoc[tag=peopleremindall]

include::../UserGuide.adoc[tag=peoplefind]

include::../UserGuide.adoc[tag=peopleclear]

== FAQ

include::../UserGuide.adoc[tag=editing-user-data]

include::../UserGuide.adoc[tag=debt-and-loan-diff]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== Design

include::../DeveloperGuide.adoc[tag=model-design]

== Implementation

include::../DeveloperGuide.adoc[tag=received_implementation]

include::../DeveloperGuide.adoc[tag=useCases]
